services:
  postgres:
    image: postgres:17-alpine
    container_name: db_i_compras
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: icomprasprodutos, icompraspedidos, icomprasclientes
    ports:
      - "5555:5432"
    volumes:
      - ./data:/var/lib/postgresql/data