spring:
  application:
    name: faturamentos
  kafka:
    bootstrap-servers: 'http://localhost:29092'
    consumer:
      group-id: icompras-faturamento
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

icompras:
  config:
    kafka:
      topics:
        pedidos-pagos: 'icompras.pedidos-pagos'
        pedidos-faturados: 'icompras.pedidos-faturados'

server:
  port: 8084
minio:
  url: 'http://localhost:9000'
  bucket-name: icompras.faturas
  access-key: minioadmin
  secret-key: minioadmin123